import { Module, Controller, Get, Post, Body, Param } from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';

@ApiTags('signals')
@Controller('signals')
export class SignalsController {
  @Get()
  getSignals() {
    return { message: 'Active AI signals — generated by Python AI service' };
  }

  @Get(':id')
  getSignal(@Param('id') id: string) {
    return { message: `Signal ${id} details` };
  }
}

@Module({ controllers: [SignalsController] })
export class SignalsModule {}
